 const names = require('./4-names')
 const sayHi = require('./5-utils')
 const data = require('./6-alternative-flavor')
require('./7-mg')
console.log(names)
console.log(data)
sayHi('SAYIII')
sayHi(names.j)
sayHi(names.p)